name: Spidey Bot

on:
  schedule:
    - cron: "13/5 * * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Debug trigger
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          date -u

      - name: Send Discord message
        run: |
          curl -f -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"$SPY"}' \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"



# refresh