name: Spidey Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord message
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"$SPY"}' \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"